### PR TITLE
transform option. 

### PR DESCRIPTION
**Pull request by CharlesHolbrow**
Hi Rollup Team, 

For my workflow, I need to preprocess data that I am saving in YAML files. It is very convenient to do this as part of the build process. See the `README.md` diff for an example. 

I would be happy to publish my own fork to NPM for this purpose. Before I do that, is your team interested in including this behavior?

If so, please let me know if the pull request needs anything beyond what is below. If this is too feature creepy, I would also be happy to maintain it myself. 

Thanks for taking a look!

### CODE REVIEW

**Comment by lukastaegert** [comment]
I think this option could definitely be merged, but for that it would need proper tests. Also @Rich-Harris would be nice if you could give me publishing rights for this repo, thanks.

**Comment by CharlesHolbrow** [comment]
Thanks, @lukastaegert I added tests. do these look good to you? Please let me know if you are willing to publish these to npm.

**Comment by CharlesHolbrow** [comment]
The pull request also includes a minor version bump.

**Review by lukastaegert — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
